### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by TolgaBkm** [LintaoPeng/U-shape_Transformer_for_Underwater_Image_Enhancement#8]
Hello!
Is it possible for you to share the dataset to be used only for academic purposes?
Cheers

**Comment by LintaoPeng** [comment]
You can download the dataset from&nbsp;
https://pan.baidu.com/s/1dqB_k6agorQBVVqCda0vjA
The password is lsui
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Thursday, Sep 8, 2022 4:20 PM
***@***.***&gt;; 
***@***.***&gt;; 
Subject: &nbsp;[LintaoPeng/U-shape_Transformer_for_Underwater_Image_Enhancement] Dataset (Issue #8)





 
Hello!
 Is it possible for you to share the dataset to be used only for academic purposes?
 Cheers

**Comment by TolgaBkm** [comment]
Thank you!
